### ISSUE TITLE
Merging broken?

### ISSUE THREAD

**Issue by AdamFrey** [mapbox/geojson-merge#17]
I installed version 1.0.1 and am trying to merge from the CLI.

No matter what combination of input files I specify, only the first file is present in the combined result, each other file is represented with a `null` item in the features list.

**Comment by tmcw** [comment]
More details, please. Are you using Windows or another unusual platform? Are the files FeatureCollections or another type? Can you provide examples of the files?

**Comment by AdamFrey** [comment]
Sorry, I could have provided more context. This is on MacOS. The files are all FeatureCollections. Here are two of the files I'm trying to merge: https://gist.github.com/AdamFrey/46eb9eee51a0cd67d843010c6c319e54

**Comment by tmcw** [comment]
Thanks! Fixed in 1.0.2

**Comment by AdamFrey** [comment]
Thank you.

**Comment by Monduiz** [comment]
I am encountering the same problem on windows. Two FeatureCollections as well.

**Comment by tmcw** [comment]
More details, please. Can you provide examples of the files? What's the input, what's the output, is there an error message. Always more details, always, please.

**Comment by Monduiz** [comment]
I am not sure I can upload the files, they are a bit bigger but we will see what I can do. The output is just the second file of the two in the command without the first.

`geojson-merge file1.geojson file2.geojson > merged.geojson`
