### ISSUE TITLE
Make criteria for using streaming mode clearer

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/geojson-merge#18]
Documentation request to make it more clear when it is required to use the streaming mode.

I am trying to combine many geojson files (>100).  Without streaming mode (no ```-s```), not all features are combined, and many (>10,000) features are simply ```null``` in the output merged file. When using ```-s```, all files are merged properly and no features come back as null. Clearly some type of limit was reached on the normal mode that caused all future files to to be properly merged.

**Comment by tmcw** [comment]
Are you using `1.0.2`? You may be running into a bug in 1.0.1 that was fixed. If geojson-merge runs into a limit, it should/will fail noisily.

**Comment by scottsfarley93** [comment]
Yep. Updating the package fixed it. Thanks! 

I still might suggest giving a bit more on the difference between streaming and normal modes.
