### ISSUE TITLE
Merging multiple files in a folder

### ISSUE THREAD

**Issue by pratikyadav** [mapbox/geojson-merge#2]
I have a dump of *.geojson files in a folder. Will it be possible to merge all of them into a single file by some thing like

`geojson-merge /folder/*.geojson > combined.geojson`

**Comment by tmcw** [comment]
Yep, that should work. Please post an error if it doesn't.

**Comment by pratikyadav** [comment]
Working :)

**Comment by jaskiratr** [comment]
Not sure why am I getting the following error.
Any help would be great. Thanks
```
geojson-merge *.geojson > combined.geojson
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\Work\Data\geojson\*.geojson'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at C:\Users\Jess\AppData\Roaming\npm\node_modules\geojson-merge\geojson-merge:16:28
    at Array.map (native)
    at Object.<anonymous> (C:\Users\Jess\AppData\Roaming\npm\node_modules\geojson-merge\geojson-merge:15:52)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by tmcw** [comment]
You're using Windows, and it doesn't support the same 'wildcard' syntax. You can use PowerShell, which should support globs, or consult the Windows documentation for the right syntax for the default shell, which I'm not sure of. It's hard to tell if globs are supported by the default Windows shell at all.

**Comment by jaskiratr** [comment]
Thank you for your swift response.
I'm using Windows 10 and running it on cmder. `ls *.geojson` works and lists all the .geojson files in the directory. Powershell behaves similarly. 
[Win Wildcard Reference](https://technet.microsoft.com/en-us/library/bb490639.aspx)

**Comment by jaskiratr** [comment]
I get following error in Ubuntu Bash running from within Windows 10.

```
root@MONARCH:/mnt/d/Work/geojson/test# geojson-merge *.geojson > combined.geojson
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/geojson-merge/geojson-merge:16:19
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/geojson-merge/geojson-merge:15:52)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

**Comment by pratikyadav** [comment]
@jaskiratr I got the same error toady while trying to merge multiple geojsons. I found out that one of the geojson was invalid i.e. was of 0kb size. It worked fine when I deleted that particular file. Not sure if it will help in your case but you might wanna check the individual geojson files.

**Comment by jaskiratr** [comment]
@pratikyadav Interesting. Are you on a Windows machine?
I'm now using Ubuntu bash from within windows. That works. 
Thanks.

**Comment by fikrifauzul** [comment]
@tmcw In Windows, my file geojson until 6.000 ++ to merge
And some error:
The filename or extension is too long. (error 0xce)

Please respone my error.

**Comment by humayunharoon** [comment]
Can you maybe document this is the readMe? I spent a good amount of time trying to achieve the following via a bash script only to run into errors

```
for file in ~/Workspace/geoJsonFilesFolder/*
do
  geojson-merge "$file" combined.json > combined.json
done
```

I would keep getting
```SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/@mapbox/geojson-merge/geojson-merge:18:19
    at Array.map (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/@mapbox/geojson-merge/geojson-merge:17:52)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
undefined:1
```

**Comment by pratikyadav** [comment]
@humayunharoon It is documented here at the bottom -> https://github.com/mapbox/geojson-merge#geojson-merge-for-dummies but feel free to open a PR if you want to add additional documentation :)

**Comment by lhclack** [comment]
> Not sure why am I getting the following error. Any help would be great. Thanks
> 
> ```
> geojson-merge *.geojson > combined.geojson
> fs.js:640
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open 'D:\Work\Data\geojson\*.geojson'
>     at Error (native)
>     at Object.fs.openSync (fs.js:640:18)
>     at Object.fs.readFileSync (fs.js:508:33)
>     at C:\Users\Jess\AppData\Roaming\npm\node_modules\geojson-merge\geojson-merge:16:28
>     at Array.map (native)
>     at Object.<anonymous> (C:\Users\Jess\AppData\Roaming\npm\node_modules\geojson-merge\geojson-merge:15:52)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
> ```

Same error in Windows here. Going to try the ubuntu bash work around, but really frustrating to not find anything that works atm
