### ISSUE TITLE
redundant geographical elements

### ISSUE THREAD

**Issue by hbsxun** [mapbox/geojson-merge#4]
Hi,All,

This code maybe simply concatenate all the geoJSON data.
However, many redundant geographical elements  also appear in the result.
How to solve this problem? Could you give me some advice? Thanks.

Kind regards,
Xun

**Comment by tmcw** [comment]
Hi Xun,

If you're looking for something that combines overlapping features, you'll want a module with a `union` method like [Turf](http://turfjs.org/).
